# Build stage
FROM node:22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod



FROM nginx:alpine
# Install bash & sed (or envsubst if you prefer)
RUN apk add --no-cache bash

COPY --from=build /app/dist/store-app-frontend/browser /usr/share/nginx/html

# Copy an entrypoint script that does the replacement
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
